
import FeaturesPage from '@/components/Features'
import HeroSection from '@/components/HeroSection'
import NavBar from '@/components/Navbar'
import Testimonials from '@/components/Testimonials'
import Head from 'next/head'
import Image from 'next/image'
import awsExports from '../src/aws-exports';
import { Amplify, API, Auth, withSSRContext } from 'aws-amplify';
Amplify.configure({ ...awsExports, ssr: true });
export default function Home() {
  return (
    <>




     
      <Head>
        <title>Your Saas name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <div>
      <NavBar/>
    <HeroSection />
    <FeaturesPage />
    <Testimonials/>
    </div>
      </main>
    </>
  )
}
